### ISSUE TITLE
MacOS support?

### ISSUE THREAD

**Issue by lebedov** [kmaork/madbg#18]
Can madbg currently be used on MacOS? I'm guessing not given that pyinjector only seems to support Linux and Windows and given that madbg raised the following exception when I tried to attach to a process on MacOS 10.15.7 with Python 3.8.8.

```
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import madbg
  File "/Users/lgivon/miniconda3/lib/python3.8/site-packages/madbg/__init__.py", line 1, in <module>
    from .api import set_trace, set_trace_on_connect, post_mortem, run_with_debugging, attach_to_process
  File "/Users/lgivon/miniconda3/lib/python3.8/site-packages/madbg/api.py", line 9, in <module>
    from hypno import inject_py
  File "/Users/lgivon/miniconda3/lib/python3.8/site-packages/hypno/__init__.py", line 1, in <module>
    from .hypno import inject_py
  File "/Users/lgivon/miniconda3/lib/python3.8/site-packages/hypno/hypno.py", line 4, in <module>
    from pyinjector import inject
  File "/Users/lgivon/miniconda3/lib/python3.8/site-packages/pyinjector/__init__.py", line 1, in <module>
    from .pyinjector import inject
  File "/Users/lgivon/miniconda3/lib/python3.8/site-packages/pyinjector/pyinjector.py", line 13, in <module>
    libinjector.injector_attach.argtypes = POINTER(injector_pointer_t), pid_t
  File "/Users/lgivon/miniconda3/lib/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/Users/lgivon/miniconda3/lib/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fa840e11c00, injector_attach): symbol not found
```

**Comment by kmaork** [comment]
You are right, pyinjector does not support OSX currently, and it seems like it might take some work to do. I'm not planning to do it myself in the near future, but any PRs are welcome 😄
