### ISSUE TITLE
Python 3.6 support

### ISSUE THREAD

**Issue by fsilvestre** [kmaork/madbg#19]
How to reproduce:
```
git clone https://github.com/kmaork/madbg.git
cd madbg/
python setup.py install
```

```
# python
Python 3.6.8 (default, Mar 19 2021, 05:13:41)
[GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import madbg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/maestro/env/lib64/python3.6/site-packages/madbg-1.1.4-py3.6.egg/madbg/__init__.py", line 1, in <module>
  File "/opt/maestro/env/lib64/python3.6/site-packages/madbg-1.1.4-py3.6.egg/madbg/api.py", line 7, in <module>
ImportError: cannot import name 'nullcontext'
```

**Comment by kmaork** [comment]
I think at this point I'm not planning to support python3.6, closing this
