### ISSUE TITLE
 AttributeError: dlsym(0x7fe7fd446100, injector_attach): symbol not found

### ISSUE THREAD

**Issue by vadimszzz** [kmaork/madbg#32]
```
x@192-168-10-195 android-apps-research-2021 % python
Python 3.9.0 (default, Sep 17 2021, 16:39:04) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import madbg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/madbg/__init__.py", line 1, in <module>
    from .api import set_trace, set_trace_on_connect, post_mortem, run_with_debugging, attach_to_process
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/madbg/api.py", line 9, in <module>
    from hypno import inject_py
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/hypno/__init__.py", line 1, in <module>
    from .hypno import inject_py
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/hypno/hypno.py", line 4, in <module>
    from pyinjector import inject
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyinjector/__init__.py", line 1, in <module>
    from .pyinjector import inject, LibraryNotFoundException
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/pyinjector/pyinjector.py", line 13, in <module>
    libinjector.injector_attach.argtypes = POINTER(injector_pointer_t), pid_t
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fe7fd446100, injector_attach): symbol not found
```

**Comment by vadimszzz** [comment]
#18

**Comment by kmaork** [comment]
Hey, making sure - this is on Mac, right?

**Comment by kmaork** [comment]
So thank you, closing this in favor of #18
