### ISSUE TITLE
Can't attach to a process on musl libc

### ISSUE THREAD

**Issue by ptrcnull** [kmaork/madbg#37]
Stacktrace:
```
Traceback (most recent call last):
  File "/usr/bin/madbg", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/madbg/__main__.py", line 34, in attach
    attach_to_process(pid, port, connect_timeout=timeout)
  File "/usr/lib/python3.9/site-packages/madbg/api.py", line 31, in attach_to_process
    _inject_set_trace(pid, ip, port)
  File "/usr/lib/python3.9/site-packages/madbg/api.py", line 25, in _inject_set_trace
    inject_py(pid, f'__import__("signal").signal({sig_num},lambda _,f:__import__("madbg").set_trace(f,"{ip}",{port}))')
  File "/usr/lib/python3.9/site-packages/hypno/hypno.py", line 20, in inject_py
    inject(pid, str(copied_lib))
  File "/usr/lib/python3.9/site-packages/pyinjector/pyinjector.py", line 95, in inject
    injector = Injector.attach(pid)
  File "/usr/lib/python3.9/site-packages/pyinjector/pyinjector.py", line 77, in attach
    call_c_func(libinjector.injector_attach, byref(injector_p), pid,
  File "/usr/lib/python3.9/site-packages/pyinjector/pyinjector.py", line 66, in call_c_func
    raise exception_cls(func.__name__, ret, libinjector.injector_error())
pyinjector.pyinjector.InjectorError: injector_attach returned -4: failed to open /usr/lib/x86_64-linux-gnu/libc-2.31.so. (error: No such file or directory)
```

**Comment by kmaork** [comment]
Waiting on https://github.com/kubo/injector/pull/22

**Comment by ptrcnull** [comment]
thanks!

**Comment by kmaork** [comment]
Hey @ptrcnull, https://github.com/kubo/injector seems a little inactive, so I created my own fork. No changes were required for madbg itself, only for dependencies - try running `pip install madbg -U` and it should be ready for use on musl processes 😄 Pleasant debugging!
