### ISSUE TITLE
Could not find libc

### ISSUE THREAD

**Issue by htjain** [kmaork/madbg#40]
getting following error while running on ubuntu docker images:

> Traceback (most recent call last):
>   File "/usr/local/bin/madbg", line 8, in <module>
>     sys.exit(cli())
>   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/local/lib/python3.8/dist-packages/madbg/__main__.py", line 34, in attach
>     attach_to_process(pid, port, connect_timeout=timeout)
>   File "/usr/local/lib/python3.8/dist-packages/madbg/api.py", line 34, in attach_to_process
>     _inject_set_trace(pid, ip, port)
>   File "/usr/local/lib/python3.8/dist-packages/madbg/api.py", line 28, in _inject_set_trace
>     inject_py(pid, f'__import__("signal").signal({sig_num},lambda _,f:__import__("madbg").set_trace(f,"{ip}",{port}))')
>   File "/usr/local/lib/python3.8/dist-packages/hypno/hypno.py", line 20, in inject_py
>     inject(pid, str(copied_lib))
>   File "/usr/local/lib/python3.8/dist-packages/pyinjector/pyinjector.py", line 95, in inject
>     injector = Injector.attach(pid)
>   File "/usr/local/lib/python3.8/dist-packages/pyinjector/pyinjector.py", line 77, in attach
>     call_c_func(libinjector.injector_attach, byref(injector_p), pid,
>   File "/usr/local/lib/python3.8/dist-packages/pyinjector/pyinjector.py", line 66, in call_c_func
>     raise exception_cls(func.__name__, ret, libinjector.injector_error())
> pyinjector.pyinjector.InjectorError: injector_attach returned -4: Could not find libc

**Comment by kmaork** [comment]
Thank you for the report @htjain!
Can you provide more details? I tried recreating the issue by:
```bash
docker run -it python:latest bash
pip3 install madbg
python -c "while 1:1" &
madbg attach $!
```
And it worked for me.

I'd like to know:
1. How you installed madbg
2. How you invoked madbg
3. What version of the ubuntu image you were using
4. How you invoked the process you tried attaching to
