### ISSUE TITLE
ModuleNotFoundError: No module named 'fcntl'

### ISSUE THREAD

**Issue by nguyenduchuyz190** [kmaork/madbg#46]
```
PS F:\Workspace\play-with-***\injector> madbg attach 20016
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main        
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts\madbg.exe\__main__.py", line 4, in <module>
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\madbg\__init__.py", line 1, in <module>
    from .api import set_trace, set_trace_on_connect, post_mortem, run_with_debugging, attach_to_process
  File "C:\Users\***\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\madbg\api.py", line 11, in <module>
    from fcntl import fcntl, F_GETFL, F_SETFL, F_SETOWN
ModuleNotFoundError: No module named 'fcntl'
```

I'm using Window 11, Python 3.10

**Comment by kmaork** [comment]
Madbg does not support windows currently.
