### ISSUE TITLE
Please document (in the readme) that this does not work for Windows

### ISSUE THREAD

**Issue by kunom** [kmaork/madbg#52]
Could you please extend the Readme to state that this is not intended to work on Windows?

The code uses many stdlib modules that are Unix-only, e.g. `fctl`:
```
Python 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import madbg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mek\AppData\Roaming\Python\Python312\site-packages\madbg\__init__.py", line 1, in <module>
    from .api import set_trace, set_trace_on_connect, post_mortem, run_with_debugging, attach_to_process
  File "C:\Users\mek\AppData\Roaming\Python\Python312\site-packages\madbg\api.py", line 11, in <module>
    from fcntl import fcntl, F_GETFL, F_SETFL, F_SETOWN
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by kunom** [comment]
I seem to have been blind...
